spring:
    application:
        name: springBootRetest
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:tcp://localhost/~/test
        username: sa


